### ISSUE TITLE
How to deploy a Pod Provider

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solid.github.io#18]

**Comment by ewingson** [comment]
I' m totally new to this workflow. the who might be @Mitzi-Laszlo or @Vinnl. the what could be an extension of https://solid.inrupt.com/docs/installing-running-nss with more user defined details and adaption dependent e.g. if NSS is used standalone/apache/nginx. I *really* would like to help, have chosen this issue well and need some guidance on the HOW. can anyone point me in the right direction to creating content/solving this issue/finding a fitting field for my effords ?

**Comment by Vinnl** [comment]
Thanks for stepping up @ewingson! The "who" for this issue would probably be @jaxoncreed, who's most familiar with the situation w.r.t. NSS and I think already has plans for what to write.

As for how: this site is a [Jekyll](https://jekyllrb.com) site, so its documentation should apply. You can find an example in [the apps tutorial](https://github.com/solid/solid.github.io/tree/master/_posts/implement/apps/first-app). But again, before putting any effort into this, be sure to discuss with @jaxoncreed to get an idea of whether it's for the effort for NSS.

**Comment by ewingson** [comment]
hey thanx, will keep the eyes open at the next panel meeting on monday (which overtaxes me a bit to be honest) or weekly call on thursday and meanwhile check out Jekyll a bit. cool, thanx for the point.

**Comment by ewingson** [comment]
@Mitzi-Laszlo @jaxoncreed 

I have begun the work. first content, then formatting. https://github.com/ewingson/solid.github.io/blob/master/pages/implement-a-pod.md

**Comment by jaxoncreed** [comment]
Thanks so much @ewingson

**Comment by ewingson** [comment]
@jaxoncreed @Vinnl @Mitzi-Laszlo 
I' ve made a draft at https://github.com/ewingson/solid.github.io/blob/master/pages/implement-a-pod.md
some questions arouse.
https://solid.github.io/for-developers/pod-server would be the site to work at I guess.
I couldn' t identify that site at https://github.com/solid/solid.github.io/tree/master/pages
due to the fact, that everything is a work in progress and the structure has already and will change again I think, how shall we continue ?
would you have a quick look at the content so far ?
a) it' s poorly formatted so far
b) we still would need even more details (kindof commandline-log of apache config e.g.)
can we sync up how to proceed ? sorry I didn' t make it in time for the user-tests.

**Comment by Vinnl** [comment]
> https://solid.github.io/for-developers/pod-server would be the site to work at I guess. 

That is correct.

> I couldn' t identify that site at https://github.com/solid/solid.github.io/tree/master/pages .

The setup is a bit unconventional, but the relevant page is located at https://github.com/solid/solid.github.io/tree/master/_posts/for-developers/pod-server

Content-wise I don't have much to say since it's not my area of expertise, although one thing that might be good to add is what system requirements you assume - I see some paths that I suppose assume Linux, might work on OS X, but I'm quite sure won't work on Windows directly :)

**Comment by ewingson** [comment]
@Vinnl @jaxoncreed 

I didn' t change the content of https://github.com/ewingson/solid.github.io/blob/master/_posts/for-developers/pod-server/2019-01-01-00_overview.md just added the stuff beneath.

before I make a PR we must consider the formatting. for example so far I left everything lowercase. I' ve used github-markdown for the code-examples. I' d like to make sure we sync up as close as possible so please have a look and let me know.
