### ISSUE TITLE
Design app tutorial layout

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solid.github.io#62]
design the content page that Vincent put together on https://github.com/solid/solid.github.io/issues/4

possible references: 

https://developer.android.com/training/basics/firstapp

https://developer.apple.com/library/archive/referencelibrary/GettingStarted/DevelopiOSAppsSwift/

**Comment by Vinnl** [comment]
Starting page link: https://solid.github.io/Build-on-Solid/writing-solid-applications

Some items in particular:

1. Ordered lists do not show the list numbers, and the font is disproportionately large: 
![image](https://user-images.githubusercontent.com/4251/66047186-a1a5e580-e527-11e9-8e28-8f7bdb0d928d.png)
2. Syntax highlighting on code snippets would be nice, although that's not really a design issue, I guess.
3. The font size for tables is disproportionately large: 
![image](https://user-images.githubusercontent.com/4251/66047259-bc785a00-e527-11e9-87ff-995b00d80902.png)

**Comment by Mitzi-Laszlo** [comment]
does this work? https://solid.github.io/learn-about-solid/what-is-solid

**Comment by justinwb** [comment]
> Starting page link: https://solid.github.io/Build-on-Solid/writing-solid-applications

@Vinnl can i find this at another link now? getting a 404 at that one.

> design the content page that Vincent put together on #4

@Mitzi-Laszlo not sure if this is a design ticket or a development one. the secondary page style that you linked in the [last comment](https://github.com/solid/solid.github.io/issues/62#issuecomment-538420323) should support the design that you suggested in the original comment. it looks like in @Vinnl's [comment](https://github.com/solid/solid.github.io/issues/62#issuecomment-537487731) that he was pointing out some specific issues with that template, but the example cited brings me to a broken link. if it's a matter of fixing the template then this would fall into the developer bucket rather than design. either is fine, just want to make sure that we scope it to the right resources.

**Comment by Vinnl** [comment]
@justinwb Sorry, we moved stuff around. The starting page is https://solid.github.io/build/apps/first-app (though click "Start" below to move through the full tutorial).

Design is the primary thing the content team can't really do themselves :)
